/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trigger_backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/collect/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trigger_collect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a single notifier pass synchronously: fan every feed-visible,
         *     un-notified mention out to its workspace's notifications, then mark them
         *     notified. Mirrors the background loop so the pipeline can be driven
         *     deterministically.
         */
        post: operations["trigger_notify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/channels` — list every channel config (global, not workspace-scoped). */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/channels/:channel` — fetch a single channel config by name.
         *     Returns 404 if the channel has never been configured.
         */
        get: operations["getChannel"];
        /**
         * `PUT /api/channels/:channel` — create or update a channel config. Body fields
         *     are all optional: `enabled`, `poll_interval` (seconds, default 900), and
         *     `credentials` (channel-specific JSON). For Reddit the only (optional) credential
         *     is `{ "user_agent" }` — Reddit's public search needs no client id/secret. For
         *     GitHub the credentials are a `{ "token", ... }` filter object. When `enabled` is
         *     omitted the channel's current enabled state is preserved. When `credentials` is
         *     omitted the previously-stored credentials are preserved (not wiped) — pass an
         *     explicit `credentials` object to change them.
         */
        put: operations["upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel}/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cleanup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel}/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/channels/{channel}/targets` — per-target collection status for a
         *     channel (watermark, last success/attempt, consecutive failures, last error,
         *     derived health) plus each target's open backfill jobs. Backend-only status view
         *     for the targeted (auto-recovering) collector pipeline.
         */
        get: operations["listChannelTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ai_config"];
        put: operations["update_ai_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/ai/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_ai_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{service}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/logs/{service}` — last N log lines for `service`.
         * @description `service` accepts any channel name (`reddit`, `hackernews`, `github`) and
         *     future services (`ai_filter`/`llm`). Unknown services → 404. The number of
         *     lines is capped (default 200, max 2000).
         */
        get: operations["getServiceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/mentions` — list mentions (keyset-paginated by the compound
         *     `before`/`before_id` cursor).
         */
        get: operations["listMentions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/pending-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/mentions/pending-count` — size + age of the AI-filter backlog,
         *     driving the feed's "N pending AI filter" banner.
         */
        get: operations["mentionsPendingCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/mentions/:id` — fetch a single mention (used by the mention
         *     detail page that web-push notifications deep-link to).
         */
        get: operations["getMention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** `PUT /api/mentions/:id/read` — mark a mention read or unread. */
        put: operations["setMentionRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/monitors?workspace_id=…` — list monitors in a workspace.
         *     The `workspace_id` query param is required.
         */
        get: operations["listMonitors"];
        put?: never;
        /**
         * `POST /api/monitors` — create a monitor watch. Body is [`CreateMonitor`]:
         *     `workspace_id` and `terms` (the match-any keyword list) are required;
         *     `channels` (empty/omitted = all channels), `exact_match`, `case_sensitive`,
         *     `exclude_terms` are optional.
         */
        post: operations["createMonitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/monitors/:id` — fetch a single monitor. */
        get: operations["getMonitor"];
        /**
         * `PUT /api/monitors/:id` — update a monitor watch. Body is [`UpdateMonitor`];
         *     every field is optional and only provided fields are changed.
         */
        put: operations["updateMonitor"];
        post?: never;
        /** `DELETE /api/monitors/:id` — delete a monitor watch (cascades to its mentions). */
        delete: operations["deleteMonitor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post: operations["createNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendTestNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVapidPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/workspaces` — list all workspaces (not workspace-scoped). */
        get: operations["listWorkspaces"];
        put?: never;
        /** `POST /api/workspaces` — create a workspace. Body: `{ name, description? }`. */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** `PUT /api/workspaces/:id` — rename/update a workspace. Body: `{ name, description? }`. */
        put: operations["updateWorkspace"];
        post?: never;
        /** `DELETE /api/workspaces/:id` — delete a workspace (cascades to its monitors and notifications). */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Partial update. Every field is optional; omitted (or null) fields are left
         *     unchanged. For `api_key`, an empty string clears the stored key.
         */
        AiConfigUpdate: {
            api_key?: string | null;
            base_url?: string | null;
            enabled?: boolean | null;
            model?: string | null;
        };
        /**
         * @description AI-filter settings as exposed to clients. The API key is never returned;
         *     `api_key_set` reports only whether one is configured.
         */
        AiConfigView: {
            api_key_set: boolean;
            base_url: string;
            enabled: boolean;
            model: string;
        };
        /** @description Result of a `test` call: a sample verdict on success, or an error message. */
        AiTestResult: {
            error?: string | null;
            ok: boolean;
            reason?: string | null;
            verdict?: string | null;
        };
        BackfillBody: {
            /** Format: int32 */
            days: number;
        };
        /**
         * @description A durable backfill job: a half-open `[range_start, range_end)` window of one
         *     target that still needs older pages walked. Survives restarts; resumes from
         *     `next_cursor`.
         */
        BackfillJob: {
            /** Format: int64 */
            attempts: number;
            /** Format: int64 */
            created_at: number;
            id: string;
            last_error?: string | null;
            /** @description The `after` token to resume paging from. */
            next_cursor?: string | null;
            /** Format: int64 */
            pages_done: number;
            /**
             * Format: int64
             * @description Newer bound — shrinks toward `range_start` as older pages are banked.
             */
            range_end: number;
            /**
             * Format: int64
             * @description Older bound (inclusive).
             */
            range_start: number;
            /** @description `open` | `done` | `abandoned`. */
            state: string;
            target_id: string;
            /** Format: int64 */
            updated_at: number;
        };
        BackfillRequest: {
            channel?: string | null;
            /** Format: int64 */
            since: number;
        };
        /** @description Result of a channel backfill: a human-readable status message. */
        BackfillResult: {
            message: string;
        };
        ChannelBody: {
            credentials?: unknown;
            enabled?: boolean | null;
            /** Format: int64 */
            poll_interval?: number | null;
        };
        ChannelConfig: {
            /**
             * Format: int64
             * @description The caught-up watermark: how far this channel is contiguously
             *     ingested. Distinct from `last_polled_at`, which is merely the last
             *     attempt time.
             */
            caught_up_at?: number | null;
            channel: string;
            credentials: unknown;
            enabled: boolean;
            error_message?: string | null;
            /** Format: int64 */
            last_polled_at?: number | null;
            /** Format: int64 */
            max_backfill_days: number;
            /** Format: int64 */
            poll_interval: number;
            /** Format: int64 */
            updated_at: number;
        };
        /**
         * @description Per-health counts plus a ready-to-display degraded message, summarizing a
         *     channel's targets at time `now`. The `message` is `None` when nothing is
         *     degraded; otherwise it leads with "rate-limited" when any target is throttled
         *     (so the banner reads as a throttle), else "degraded".
         */
        ChannelHealthSummary: {
            /** @description Targets that are throttled or failing (the banner count). */
            degraded: number;
            failing: number;
            healthy: number;
            idle: number;
            /** @description A human-readable degraded summary, or `None` when all targets are fine. */
            message?: string | null;
            throttled: number;
            total: number;
        };
        CleanupBody: {
            dry_run: boolean;
        };
        /**
         * @description Preview returned by a dry-run cleanup: how many mentions would be removed,
         *     plus up to 10 samples.
         */
        CleanupPreview: {
            count: number;
            sample: components["schemas"]["MentionSample"][];
        };
        /**
         * @description A cleanup call returns a preview on `dry_run` and a delete count otherwise.
         *     Untagged so the wire shape is exactly one of the two inner objects.
         */
        CleanupResponse: components["schemas"]["CleanupPreview"] | components["schemas"]["CleanupResult"];
        /** @description Result of a real (non-dry-run) cleanup: how many mentions were deleted. */
        CleanupResult: {
            /** Format: int64 */
            deleted: number;
        };
        /**
         * @description A durable collection target: one consolidated upstream request (an OR-batched
         *     global search, or a per-sub search) that the targeted
         *     runner pages, banks progress for, and tracks sticky failure status on.
         */
        CollectorTarget: {
            channel: string;
            /**
             * Format: int64
             * @description Timestamp below which this target has been contiguously ingested. The
             *     channel is "caught up" only when all its targets' watermarks are recent.
             */
            confirmed_watermark?: number | null;
            /** Format: int64 */
            consecutive_failures: number;
            /** @description Sub-list or query — human-readable, and the basis for `id`. */
            descriptor: string;
            /** @description Stable id derived from `channel + kind + descriptor`. */
            id: string;
            /** @description `feed` | `search`. */
            kind: string;
            /** Format: int64 */
            last_attempt_at?: number | null;
            /**
             * @description Sticky: a different target succeeding does NOT clear this. Display/health
             *     only — pacing is governed globally by the adaptive rate limiter, not a
             *     per-target backoff.
             */
            last_error?: string | null;
            /** Format: int64 */
            last_success_at?: number | null;
            /** Format: int64 */
            updated_at: number;
        };
        CreateMonitor: {
            /** @description AI relevance prompt; empty/whitespace is normalized to "disabled". */
            ai_filter_prompt?: string | null;
            case_sensitive?: boolean | null;
            /** @description Per-channel collection overrides keyed by channel name. */
            channel_settings?: unknown;
            channels?: string[] | null;
            exact_match?: boolean | null;
            exclude_terms?: string[] | null;
            /**
             * @description Match-any term list (each a bare literal phrase). A post matches if it
             *     contains ANY term and none of `exclude_terms`.
             */
            terms: string[];
            workspace_id: string;
        };
        /** @description Create request for a notification. */
        CreateNotification: {
            /**
             * @description Kind-specific config JSON (webpush: `{endpoint,p256dh,auth}`; webhook:
             *     `{url}`).
             */
            config: unknown;
            /** @description `webpush` | `webhook`. */
            kind: string;
            label?: string | null;
            workspace_id: string;
        };
        /**
         * @description Response body: the resolved service, the lines (oldest → newest), and
         *     whether the underlying log file existed.
         */
        LogResponse: {
            exists: boolean;
            lines: string[];
            service: string;
        };
        Mention: {
            /** @description The judge's one-sentence explanation for the verdict. */
            ai_reason?: string | null;
            /**
             * @description AI filter verdict: `None` = no AI filtering applied, `pending` =
             *     awaiting judgment (hidden from the feed), `accepted` / `rejected`.
             */
            ai_verdict?: string | null;
            author_name?: string | null;
            author_url?: string | null;
            channel: string;
            content_text: string;
            content_url: string;
            external_id: string;
            id: string;
            /** Format: int64 */
            ingested_at: number;
            monitor_id: string;
            platform_meta: unknown;
            /** Format: int64 */
            published_at?: number | null;
            /**
             * Format: int64
             * @description When the user marked this mention read; `None` = unread.
             */
            read_at?: number | null;
        };
        /** @description A page of mentions plus a cursor hint for keyset pagination. */
        MentionPage: {
            has_more: boolean;
            items: components["schemas"]["Mention"][];
        };
        MentionSample: {
            author?: string | null;
            id: string;
            repo?: string | null;
            title: string;
            url: string;
        };
        Monitor: {
            active: boolean;
            /**
             * @description When set, this monitor's new mentions are held out of the feed until
             *     the AI judge accepts them against this prompt.
             */
            ai_filter_prompt?: string | null;
            case_sensitive: boolean;
            /**
             * @description Per-channel collection overrides, keyed by channel name (e.g.
             *     `{"reddit": {"subreddits": ["accessibility"]}}`). Shallow-merged over
             *     the channel's global credentials at collection time; monitor keys win.
             */
            channel_settings: unknown;
            channels: string[];
            /** Format: int64 */
            created_at: number;
            exact_match: boolean;
            exclude_terms: string[];
            id: string;
            /**
             * @description Match-any keyword/phrase list: a post matches this monitor if it contains
             *     ANY of these terms (per `exact_match` / `case_sensitive`) and none of
             *     `exclude_terms`. Each term is a bare literal phrase — never OR/quotes.
             */
            terms: string[];
            /** Format: int64 */
            updated_at: number;
            workspace_id: string;
        };
        /**
         * @description A per-workspace notification: a pure delivery endpoint. Every mention that
         *     enters the feed fans out to ALL notifications in its workspace — there is no
         *     matching, criteria, per-monitor toggle, or frequency. `kind` selects the
         *     transport and `config` is the kind-specific JSON:
         *     - `webpush`: `{ endpoint, p256dh, auth }` (the browser's subscription)
         *     - `webhook`: `{ url }`
         */
        Notification: {
            config: unknown;
            /** Format: int64 */
            created_at: number;
            id: string;
            kind: string;
            label?: string | null;
            workspace_id: string;
        };
        /**
         * @description Size and age of the AI-filter backlog for a workspace — how many mentions
         *     are still awaiting a verdict (withheld from the feed) and when the oldest was
         *     ingested. The feed shows a "N pending AI filter" banner once the oldest has
         *     aged past a staleness threshold.
         */
        PendingCount: {
            /** Format: int64 */
            count: number;
            /**
             * Format: int64
             * @description `ingested_at` (epoch seconds) of the oldest pending mention, or `null`
             *     when nothing is pending.
             */
            oldest_ingested_at?: number | null;
        };
        /** @description Body for [`set_read`]. */
        SetReadRequest: {
            /** @description `true` marks the mention read, `false` marks it unread. */
            read: boolean;
        };
        /**
         * @description Coarse health of one collection target, derived purely from its sticky
         *     status fields. This is the *single source of truth* for both the per-target
         *     status badge (`GET /api/channels/{channel}/targets`) and the channel-level
         *     degraded summary — both call [`target_health`] / [`summarize_targets`], so a
         *     banner count can never drift from the table. It is time-independent: with
         *     throttling governed globally by the rate limiter (no per-target backoff
         *     clock), a target's health depends only on its latest attempt outcome.
         * @enum {string}
         */
        TargetHealth: "healthy" | "idle" | "throttled" | "failing";
        /**
         * @description Per-channel collection status: every durable target with its watermark and
         *     sticky failure status, plus a summary of its open backfill jobs.
         */
        TargetStatus: components["schemas"]["CollectorTarget"] & {
            /**
             * @description Coarse health derived from the sticky status fields (the same classifier
             *     the channel-level degraded banner counts), computed live at request time.
             */
            health: components["schemas"]["TargetHealth"];
            /** @description Open backfill jobs for this target (durable, survive restart). */
            open_jobs: components["schemas"]["BackfillJob"][];
        };
        /** @description The response for `GET /api/channels/{channel}/targets`. */
        TargetsResponse: {
            channel: string;
            /**
             * @description Per-health counts + a degraded banner message, computed from the same
             *     classifier as each target's `health`, so the banner can't disagree with
             *     the per-target list.
             */
            summary: components["schemas"]["ChannelHealthSummary"];
            targets: components["schemas"]["TargetStatus"][];
            throttle?: null | components["schemas"]["ThrottleState"];
        };
        /**
         * @description Result of sending a test notification: how many of the workspace's
         *     notifications it attempted to deliver to.
         */
        TestNotificationResult: {
            delivered: number;
        };
        /**
         * @description A snapshot of a channel's live adaptive rate-limiter (the shared lane all of
         *     the channel's targets pace through). Surfaced so the UI can watch the
         *     interval converge as the limiter adapts.
         */
        ThrottleState: {
            /**
             * Format: double
             * @description The current minimum spacing between requests, in seconds.
             */
            interval_secs: number;
            /**
             * @description Whether issuance is currently gated to a future instant (a hard
             *     `Retry-After` pause, or simply the next paced slot).
             */
            paused: boolean;
            /**
             * Format: double
             * @description The current effective issuance rate, in requests per minute (`rate_per_sec * 60`).
             */
            rate_per_min: number;
        };
        UpdateMonitor: {
            active?: boolean | null;
            /** @description AI relevance prompt; pass an empty string to clear. */
            ai_filter_prompt?: string | null;
            case_sensitive?: boolean | null;
            /** @description Per-channel collection overrides; pass `{}` to clear. */
            channel_settings?: unknown;
            channels?: string[] | null;
            exact_match?: boolean | null;
            exclude_terms?: string[] | null;
            /** @description Replace the match-any term list. Omit to leave it unchanged. */
            terms?: string[] | null;
        };
        /**
         * @description The server's VAPID public key (base64url, uncompressed P-256 point) — the
         *     browser needs it as `applicationServerKey` when subscribing.
         */
        VapidPublicKey: {
            key: string;
        };
        Workspace: {
            /** Format: int64 */
            created_at: number;
            description?: string | null;
            id: string;
            name: string;
            /** Format: int64 */
            updated_at: number;
        };
        WorkspaceBody: {
            description?: string | null;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    trigger_backfill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Single-channel backfill complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description All-channel backfill accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_collect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection run triggered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_notify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notify pass executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfig"][];
                };
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfig"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfig"];
                };
            };
        };
    };
    backfill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResult"];
                };
            };
        };
    };
    cleanup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
        };
    };
    listChannelTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel name */
                channel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsResponse"];
                };
            };
        };
    };
    get_ai_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConfigView"];
                };
            };
        };
    };
    update_ai_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiConfigUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConfigView"];
                };
            };
            /** @description Invalid settings (e.g. enabled without base_url/model) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_ai_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTestResult"];
                };
            };
        };
    };
    getServiceLogs: {
        parameters: {
            query?: {
                /** @description Max lines to return (default 200, max 2000) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Service id: a channel name or ai_filter/llm */
                service: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
            /** @description Unknown service */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMentions: {
        parameters: {
            query?: {
                workspace_id?: string | null;
                channel?: string | null;
                monitor_id?: string | null;
                limit?: number | null;
                /**
                 * @description Upper bound (exclusive) on the effective timestamp (`published_at`,
                 *     or `ingested_at` when `published_at` is null). For the feed's
                 *     keyset-pagination cursor, pair this with `before_id` — the `id` of
                 *     the last item on the previous page — so rows tied on the effective
                 *     timestamp are still visited exactly once when paging one page at a
                 *     time; `before` alone has no tiebreak.
                 */
                before?: number | null;
                /**
                 * @description Tiebreaker id paired with `before` for keyset pagination — the `id`
                 *     of the last item on the previous page. See `before`.
                 */
                before_id?: string | null;
                /** @description Lower bound: return mentions published at or after this epoch. */
                since?: number | null;
                /**
                 * @description Filter by read state: `true` = read only, `false` = unread only,
                 *     omitted = both.
                 */
                read?: boolean | null;
                /**
                 * @description AI verdict filter: omitted/`visible` = feed default (no verdict or
                 *     `accepted`); `all` = everything; `pending` / `accepted` / `rejected`
                 *     = exactly that verdict.
                 */
                ai?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionPage"];
                };
            };
        };
    };
    mentionsPendingCount: {
        parameters: {
            query?: {
                /** @description Scope the count to a single workspace; omitted = all workspaces. */
                workspace_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCount"];
                };
            };
        };
    };
    getMention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mention id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mention"];
                };
            };
            /** @description Mention not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMentionRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mention id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mention"];
                };
            };
            /** @description Mention not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMonitors: {
        parameters: {
            query: {
                workspace_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"][];
                };
            };
        };
    };
    createMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMonitor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
        };
    };
    getMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMonitor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monitor"];
                };
            };
        };
    };
    deleteMonitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listNotifications: {
        parameters: {
            query: {
                workspace_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    createNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    sendTestNotification: {
        parameters: {
            query: {
                workspace_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestNotificationResult"];
                };
            };
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVapidPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VapidPublicKey"];
                };
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
